language: cpp
dist: trusty
matrix:
  include:
  - os: linux
    env: PYTHON=2.7
  - os: linux
    env: PYTHON=3.5
  - os: linux
    env: PYTHON=3.6

before_install:
- |
  export CXX=g++-4.8 CC=gcc-4.8;
  pip install --user --upgrade pip virtualenv pytest
  virtualenv -p python$PYTHON venv
  source venv/bin/activate

install:
- |
  python setup.py sdist
  pip install --verbose dist/*.tar.gz

script:
- pytest tests