language: cpp
dist: trusty
matrix:
  include:
  - os: linux
    env: PYTHON=2.7
  - os: linux
    env: PYTHON=3.5
  - os: osx
    env: PYTHON=2.7
  - os: osx
    env: PYTHON=3.6
before_install:
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-4.8 CC=gcc-4.8; fi
  if [ -n "$PYTHON" ]; then
    if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "${PYTHON:0:1}" = "3" ]; then
      brew update; brew install python3;
    fi
    pip install --user --upgrade pip virtualenv pytest
    virtualenv -p python$PYTHON venv
    source venv/bin/activate
  fi
install:
- |
  if [ -n "$PYTHON" ]; then
    python setup.py sdist
    pip install --verbose dist/*.tar.gz
  fi
script:
- pytest tests