sudo: required

language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - sleep 1
install:
  - pip install pytest
  - pip install .
before_script:
  - sleep 1
script:
  - pytest tests
after_success:
  - sleep 1